services:
    http:
        class: AppBundle\Service\Http

framework:
    secret: %secret%
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
    templating:
        engines: [twig]
    profiler:
        enabled: %kernel.debug%
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    form: ~

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: %log_action_level%
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'AppBundle' ]
    write_to:       %kernel.root_dir%/web/

    filters:
        cssrewrite: ~
    assets:
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/vendor/twitter/bootstrap/dist/js/bootstrap.js
            output: "js/bootstrap.js"
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/vendor/twitter/bootstrap/dist/css/bootstrap.css
                - %kernel.root_dir%/vendor/twitter/bootstrap/dist/css/bootstrap-theme.css
            filters: [cssrewrite]
            output: "css/bootstrap.css"

        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/vendor/twitter/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"

        jquery:
            inputs:
                - %kernel.root_dir%/vendor/jquery/jquery/jquery-1.9.1.js
            output: "js/jquery.js"

doctrine:
    dbal:
        driver:   '%database_driver%'
        host:     '%database_host%'
        dbname:   '%database_name%'
        user:     '%database_user%'
        password: '%database_password%'
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
